name    'justintime-localmounts'
version '0.0.1'
source 'UNKNOWN'
author 'Justin Ellison <justin@techadvise.com'
license 'UNKNOWN'
summary 'Custom fact that returns all local mountpoints currently mounted'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
